config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/tolk', :as => 'tolk' if Rails.env=='development'

  root :to => 'todos#index'

  post 'mailgun/mime' => 'mailgun#mailgun'

  post 'login' => 'login#login'
  get 'login' => 'login#login'
  get 'login/check_expiry' => 'login#check_expiry'
  get 'logout' => 'login#logout'

  get "tickler" => "todos#list_deferred"
  get 'review' => "projects#review"
  get 'calendar' => "calendar#show"
  get 'done' => "stats#done", :as => 'done_overview'

  get 'search' => 'search#index'
  post 'search/results' => 'search#results', :via => 'post'

  get 'data' => "data#index"
  get 'data/csv_notes' => 'data#csv_notes'
  get 'data/yaml_export' => 'data#yaml_export'
  get 'data/xml_export' => 'data#xml_export'
  get 'data/csv_actions' => 'data#csv_actions'

  get 'integrations' => "integrations#index"
  get 'integrations/rest_api' => "integrations#rest_api", :as => 'rest_api_docs'
  post 'integrations/cloudmailin' => 'integrations#cloudmailin'
  get 'integrations/search_plugin' => "integrations#search_plugin", :as => 'search_plugin'

  get 'preferences' => "preferences#index"
  get 'preferences/render_date_format' => "preferences#render_date_format"

  get 'feeds' => "feedlist#index", :as => 'feeds'
  get 'feedlist/get_feeds_for_context' => 'feedlist#get_feeds_for_context'
  get 'feedlist/get_feeds_for_project' => 'feedlist#get_feeds_for_project'

  get 'stats' => 'stats#index'
  get 'stats/actions_done_last12months_data' => 'stats#actions_done_last12months_data'
  get 'stats/actions_done_last_years' => 'stats#actions_done_last_years'
  get 'stats/actions_done_lastyears_data' => 'stats#actions_done_lastyears_data'
  get 'stats/actions_done_last30days_data' => 'stats#actions_done_last30days_data'
  get 'stats/actions_completion_time_data' => 'stats#actions_completion_time_data'
  get 'stats/actions_running_time_data' => 'stats#actions_running_time_data'
  get 'stats/actions_visible_running_time_data' => 'stats#actions_visible_running_time_data'
  get 'stats/actions_open_per_week_data' => 'stats#actions_open_per_week_data'
  get 'stats/context_total_actions_data' => 'stats#context_total_actions_data'
  get 'stats/context_running_actions_data' => 'stats#context_running_actions_data'
  get 'stats/actions_day_of_week_all_data' => 'stats#actions_day_of_week_all_data'
  get 'stats/actions_day_of_week_30days_data' => 'stats#actions_day_of_week_30days_data'
  get 'stats/actions_time_of_day_all_data' => 'stats#actions_time_of_day_all_data'
  get 'stats/actions_time_of_day_30days_data' => 'stats#actions_time_of_day_30days_data'
  get 'stats/show_selected_actions_from_chart/:id' => 'stats#show_selected_actions_from_chart', :as => 'show_actions_from_chart'

  resources :contexts do
    member do
      get 'done_todos'
      get 'all_done_todos'
    end
    collection do
      post 'order'
      get 'done'
    end
    resources :todos
  end

  resources :projects do
    member do
      get 'done_todos'
      get 'all_done_todos'
      get 'set_reviewed'  # TODO: convert to PUT/POST
    end
    collection do
      get 'done'
      post 'order'
      post 'alphabetize'
      post 'actionize'
    end
    resources :todos
  end

  resources :todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
      put 'defer'
      get 'show_notes'
      get 'convert_to_project' # TODO: convert to PUT/POST
      delete 'remove_predecessor' # TODO: convert to PUT/POST
      post 'change_context'
    end
    collection do
      get 'done'
      get 'all_done'
      post 'check_deferred'
      post 'filter_to_context'
      post 'filter_to_project'
      post 'add_predecessor'
    end
  end

  # match /todos/tag and put everything in :name, including extensions like .m and .txt.
  # This means the controller action needs to parse the extension and set format/content type
  # Needed for /todos/tag/first.last.m to work
  get 'todos/tag/:name' => 'todos#tag', :as => :tag, :format => false, :name => /.*/
  
  get 'attachments/:id/:filename' => "todos#attachment"
  get 'tags.autocomplete' => "todos#tags", :format => 'autocomplete'
  get 'todos/done/tag/:name' => "todos#done_tag", :as => :done_tag
  get 'todos/all_done/tag/:name' => "todos#all_done_tag", :as => :all_done_tag
  get 'auto_complete_for_predecessor' => 'todos#auto_complete_for_predecessor'
  get 'mobile' => 'todos#index', :format => 'm'
  get 'm' => 'todos#index', :format => 'm'

  resources :recurring_todos do
    member do
      put 'toggle_check'
      put 'toggle_star'
    end
    collection do
      get 'done'
    end
  end

  resources :users do
    member do
      get 'change_password'
      get 'change_auth_type'
      get 'complete'
      post 'update_password'
      post 'update_auth_type'
      post 'refresh_token'
    end
  end
  get 'signup' => "users#new"

  resources :notes
  resources :preferences

  resources :data do
    collection do
      get :import
      post :csv_map
      post :csv_import
    end
  end

end

app/models/stats/projects.rb
module Stats
  class Projects

    attr_reader :user
    def initialize(user)
      @user = user
    end

    def runtime
      @runtime ||= find_top10_longest_running_projects
    end

    def actions
      @actions ||= Stats::TopProjectsQuery.new(user).result
    end

    def actions_last30days
      @actions_last30days ||= Stats::TopProjectsQuery.new(user, 1.month.ago.beginning_of_day).result
    end

    private

    def find_top10_longest_running_projects
      projects = user.projects.order('created_at ASC')
      projects.sort_by{ |p| p.running_time }.take(10)
    end

  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  helper :application, :todos, :notes
  before_filter :set_source_view
  before_filter :set_project_from_params, :only => [:update, :destroy, :show, :edit, :set_reviewed]
  before_filter :default_context_filter, :only => [:create, :update]
  skip_before_filter :login_required, :only => [:index]
  prepend_before_filter :login_or_feed_token_required, :only => [:index]

  def index
    @source_view = params['_source_view'] || 'project_list'
    if params[:projects_and_actions]
      projects_and_actions
    else
      @contexts = current_user.contexts
      init_not_done_counts(['project'])
      init_project_hidden_todo_counts(['project'])
      if params[:only_active_with_no_next_actions]
        @projects = current_user.projects.active.select { |p| count_undone_todos(p) == 0  }
      else
        @projects = current_user.projects
      end
      @active_projects = current_user.projects.active
      @hidden_projects = current_user.projects.hidden
      respond_to do |format|
        format.html  do
          @page_title = t('projects.list_projects')
          @count = current_user.projects.count
          @completed_projects = current_user.projects.completed.limit(10)
          @completed_count = current_user.projects.completed.count
          @no_projects = current_user.projects.empty?
          current_user.projects.cache_note_counts
          @new_project = current_user.projects.build
        end
        format.m     do
          @completed_projects = current_user.projects.completed
          @down_count = @active_projects.size + @hidden_projects.size + @completed_projects.size
          cookies[:mobile_url]= {:value => request.fullpath, :secure => SITE_CONFIG['secure_cookies']}
        end
        format.xml   { render :xml => @projects.to_xml( :except => :user_id )  }
        format.any(:rss, :atom) do
          @feed_title = I18n.t('models.project.feed_title')
          @feed_description = I18n.t('models.project.feed_description', :username => current_user.display_name)
        end
        format.text do
          # somehow passing Mime::TEXT using content_type to render does not work
          headers['Content-Type']=Mime::TEXT.to_s
        end
        format.autocomplete do
          projects = current_user.projects.active + current_user.projects.hidden
          render :text => for_autocomplete(projects, params[:term])
        end
      end
    end
  end

  def review
    @source_view = params['_source_view'] || 'review'
    @page_title = t('projects.list_reviews')
    @projects = current_user.projects.load
    @contexts = current_user.contexts.load
    @projects_to_review = current_user.projects.select  {|p| p.needs_review?(current_user)}
    @stalled_projects = current_user.projects.select  {|p| p.stalled?}
    @blocked_projects = current_user.projects.select  {|p| p.blocked?}
    @current_projects = current_user.projects.uncompleted.select  {|p| not(p.needs_review?(current_user))}

    init_not_done_counts(['project'])
    init_project_hidden_todo_counts(['project'])
    current_user.projects.cache_note_counts

    @page_title = t('projects.list_reviews')
    @count = @projects_to_review.count + @blocked_projects.count + @stalled_projects.count + @current_projects.count

    @no_projects = current_user.projects.empty?
    @new_project = current_user.projects.build
  end

  def done
    @source_view = params['_source_view'] || 'project_list'
    @page_title = t('projects.list_completed_projects')

    items_per_page = 20
    page = params[:page] || 1
    @projects = current_user.projects.completed.paginate :page => page, :per_page => items_per_page
    @count = @projects.count
    @total = current_user.projects.completed.count
    @no_projects = @projects.empty?

    @range_low = (page.to_i-1) * items_per_page + 1
    @range_high = @range_low + @projects.size - 1

    @range_low = 0 if @total == 0
    @range_high = @total if @range_high > @total

    init_not_done_counts(['project'])
  end

  def set_reviewed
    @project.last_reviewed = Time.zone.now
    @project.save

    case @source_view
    when "project"
      redirect_to :action => 'show'
    when "project_list"
      redirect_to :action => 'index'
    when "review"
      redirect_to :action => 'review'
    else
      redirect_to :action => 'index'
    end
  end

  def projects_and_actions
    @projects = current_user.projects.active
    respond_to do |format|
      format.text  {
        # somehow passing Mime::TEXT using content_type to render does not work
        headers['Content-Type']=Mime::TEXT.to_s
        render :action => 'index_text_projects_and_actions', :layout => false, :content_type => Mime::TEXT
      }
    end
  end

  def show
    @max_completed = current_user.prefs.show_number_completed
    init_data_for_sidebar unless mobile?
    @page_title = t('projects.page_title', :project => @project.name)

    @not_done_todos = @project.todos.active_or_hidden.includes(Todo::DEFAULT_INCLUDES)
    @deferred_todos = @project.todos.deferred.includes(Todo::DEFAULT_INCLUDES)
    @pending_todos = @project.todos.pending.includes(Todo::DEFAULT_INCLUDES)
    @contexts_to_show = current_user.contexts.active
    @projects_to_show = [@project]

    @done = {}
    @done = @project.todos.completed.
      reorder("todos.completed_at DESC").
      limit(current_user.prefs.show_number_completed).
      includes(Todo::DEFAULT_INCLUDES) unless @max_completed == 0

    @down_count = @not_done_todos.size + @deferred_todos.size + @pending_todos.size
    @count=@down_count
    @next_project = current_user.projects.next_from(@project)
    @previous_project = current_user.projects.previous_from(@project)
    @default_tags = @project.default_tags
    @new_note = current_user.notes.new
    @new_note.project_id = @project.id
    @contexts = current_user.contexts
    respond_to do |format|
      format.html
      format.m     do
        if @project.default_context.nil?
          @project_default_context = t('projects.no_default_context')
        else
          @project_default_context = t('projects.default_context', :context => @project.default_context.name)
        end
        cookies[:mobile_url]= {:value => request.fullpath, :secure => SITE_CONFIG['secure_cookies']}
        @mobile_from_project = @project.id
      end
      format.xml   do
        render :xml => @project.to_xml(:except => :user_id) { |xml|
          xml.not_done { @not_done_todos.each { |child| child.to_xml(:builder => xml, :skip_instruct => true) } }
          xml.deferred { @deferred_todos.each { |child| child.to_xml(:builder => xml, :skip_instruct => true) } }
          xml.pending { @pending_todos.each { |child| child.to_xml(:builder => xml, :skip_instruct => true) } }
          xml.done { @done.each { |child| child.to_xml(:builder => xml, :skip_instruct => true) } }
        }
      end
    end
  end

  def create
    if params[:format] == 'application/xml' && params['exception']
      render_failure "Expected post format is valid xml like so: <project><name>project name</name></project>.", 400
      return
    end
    @project = current_user.projects.build(project_params)
    @go_to_project = params['go_to_project']
    @saved = @project.save
    @project_not_done_counts = { @project.id => 0 }
    @active_projects_count = current_user.projects.active.count
    @contexts = current_user.contexts

    respond_to do |format|
      format.js do
        @down_count = current_user.projects.size
        init_not_done_counts
      end
      format.xml do
        if @project.new_record?
          render_failure @project.errors.to_xml.html_safe, 409
        else
          head :created, :location => project_url(@project), :text => @project.id
        end
      end
      format.html {redirect_to :action => 'index'}
    end
  end

  # Edit the details of the project
  #
  def update
    template = ""

    params['project'] ||= {}
    if params['project']['state']
      @new_state = params['project']['state']
      @state_changed = @project.state != @new_state
      params['project'].delete('state')
    end
    success_text = if params['field'] == 'name' && params['value']
      params['project']['id'] = params['id']
      params['project']['name'] = params['value']
    end

    @project.attributes = project_params
    @saved = @project.save
    if @saved
      @project.transition_to(@new_state) if @state_changed
      if boolean_param('wants_render')
        @contexts = current_user.contexts
        update_state_counts
        init_data_for_sidebar
        init_project_hidden_todo_counts(['project'])

        template = 'projects/update'

      # TODO: are these params ever set? or is this dead code?
      elsif boolean_param('update_status')
        template = 'projects/update_status'
      elsif boolean_param('update_default_context')
        @initial_context_name = @project.default_context.name
        template = 'projects/update_default_context'
      elsif boolean_param('update_default_tags')
        template = 'projects/update_default_tags'
      elsif boolean_param('update_project_name')
        # clicking on a project name in the project view gives a form triggering this
        @projects = current_user.projects
        template = 'projects/update_project_name'
      else
        render :text => success_text || 'Success'
        return
      end
    else
      init_data_for_sidebar
      template = 'projects/update'
    end

    respond_to do |format|
      format.js { render :template => template }
      format.html { redirect_to :action => 'index'}
      format.xml {
        if @saved
          render :xml => @project.to_xml( :except => :user_id )
        else
          render :text => "Error on update: #{@project.errors.full_messages.inject("") {|v, e| v + e + " " }}", :status => 409
        end
      }
    end

  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def destroy

app/helpers/projects_helper.rb
module ProjectsHelper

  def show_project_name(project)
    if source_view_is :project
      content_tag(:span, :id => "project_name"){project.name}
    else
      link_to_project( project )
    end
  end

  def show_project_settings(project)
    content_tag(:div, :id => dom_id(project, "container"), :class=>"list") do
      render :partial => "projects/project_settings", :object => project
    end
  end

  def project_next_prev
    content_tag(:div, :id=>"project-next-prev") do
      html = ""
      html << link_to_project(@previous_project, "&laquo; #{@previous_project.shortened_name}".html_safe) if @previous_project
      html << " | " if @previous_project && @next_project
      html << link_to_project(@next_project, "#{@next_project.shortened_name} &raquo;".html_safe) if @next_project
      html.html_safe
    end
  end

  def project_next_prev_mobile
    prev_project = ""
    next_project = ""
    prev_project = content_tag(:li, link_to_project_mobile(@previous_project, "5", @previous_project.shortened_name), :class=>"prev") if @previous_project
    next_project = content_tag(:li, link_to_project_mobile(@next_project, "6", @next_project.shortened_name), :class=>"next") if @next_project
    return content_tag(:ul, "#{prev_project}#{next_project}".html_safe, :class=>"next-prev-project")
  end

  def project_summary(project)
    project_description = ''
    project_description += Tracks::Utils.render_text( project.description ) if project.description.present?
    project_description += content_tag(:p,
      "#{count_undone_todos_phrase(p)}. #{t('projects.project_state', :state => project.state)}".html_safe
      )
  end

  def needsreview_class(item)
    raise "item must be a Project " unless item.kind_of? Project
    return item.needs_review?(current_user) ? "needsreview" : "needsnoreview"
  end

  def link_to_delete_project(project, descriptor = sanitize(project.name))
    link_to_delete(:project, project, descriptor)
  end

  def link_to_edit_project (project, descriptor = sanitize(project.name))
    link_to_edit(:project, project, descriptor)
  end

end

app/views/projects/_project.html.erb
<%
@not_done = @not_done_todos.select {|t| t.project_id == project.id }
# invalidate the cache every day because of staleness or
# rendering of "due in x days" that change without touching updated at of the todo
cache [project, source_view_key, current_user.date.strftime("%Y%m%d"), @tag_name] do
-%>
  <%=
    title = source_view_is(:project) ? t('projects.actions_in_project_title') : show_project_name(project)

    render(:partial => 'todos/collection',
      :object => @not_done,
      :locals => { :settings => {
        :id => "p#{project.id}",
        :collapsible => settings[:collapsible],
        :title => title,
        :container_name => 'project',
        :show_empty_containers => settings[:show_empty_containers],
        :parent_container_type => settings[:parent_container_type]
      }})
  %>
<% end -%>

app/views/projects/_project_listing.m.erb
<% project = project_listing -%>
<div id="pjr"><%=
  link_to(project.name, project_path(project, :format => 'm')) +
    " (" + count_undone_todos_and_notes_phrase(project) + ")" %></div>

app/views/projects/_project_state_group.html.erb
<%-
  total_count ||= -1
  total_count_string = total_count!=-1 ? " / #{total_count}" : ""
  suppress_sort_menu ||= false
  suppress_drag_handle ||= false
-%>
<div class="project-state-group" id="list-<%= state %>-projects-container" <%= " style=\"display:none\"" if project_state_group.empty? %>>
  <h2>
    <span id="<%= state %>-projects-count" class="badge"><%= project_state_group.length%><%= total_count_string%></span>

    <%= t('common.last' ) if state == 'completed' %>
    <%= t('states.projects.'+state) %>
    <%= total_count==-1 ? "" : " (#{link_to(t('common.show_all'), done_projects_path)})".html_safe%>

  </h2>
  <% unless suppress_sort_menu %>
  <div class="menu_sort"><span class="sort_separator"><%= t('common.sort.sort') %>&nbsp;</span>
    <div class="alpha_sort">
      <%= link_to(t("common.sort.alphabetically"), alphabetize_projects_path(:state => state),
        :id => "#{state}_alphabetize_link", :class => "alphabetize_link", :title => t('common.sort.alphabetically_title'), :x_confirm_message => t('common.sort.alphabetically_confirm')) %>
    </div><span class="sort_separator">&nbsp;|&nbsp;</span><div class="tasks_sort">
      <%= link_to(t("common.sort.by_task_count"), actionize_projects_path(:state => state),
        :id => "#{state}_actionize_link", :class => "actionize_link", :title => t('common.sort.by_task_count_title'), :x_confirm_message => t('common.sort.by_task_count_title_confirm')) %>
    </div>
  </div>
  <% end %>

  <div id="list-<%= state %>-projects" class="project-list">
    <%= render :partial => 'projects/project_listing', :collection => project_state_group, :locals => {:suppress_drag_handle => suppress_drag_handle} %>
  </div>
</div>

app/views/projects/actionize.js.erb
new_html = "<%= escape_javascript(render(:partial => 'project_listing', :collection => @projects)) %>";
$("#list-<%=@state%>-projects").html(new_html);

app/views/projects/alphabetize.js.erb
new_html = "<%= escape_javascript(render(:partial => 'project_listing', :collection => @projects)) %>";
$("#list-<%=@state%>-projects").html(new_html);

app/views/projects/create.js.erb
<% unless @saved -%>
  TracksPages.show_errors(html_for_error_messages());

  function html_for_error_messages() {
    return "<%= js_error_messages_for(@project) %>";
  }
<% else -%>
  <% if @go_to_project -%>
    redirect_to("<%= project_path(@project) -%>")
  <% else -%>
  TracksPages.hide_errors();
  hide_empty_message();
  TracksPages.set_page_badge(<%= @down_count %>);
  update_active_projects_container();
  add_project();
  clear_form();
  TracksPages.page_inform("Created new project '<%= @project.name%>'");
  <% end -%>

/* TODO: make this generic for all pages with lists */
function hide_empty_message() {
  $('projects-empty-nd').hide();
}

/* TODO: refactor and move this to application.js */
function add_project() {
  $('#list-active-projects').append(html_for_project_listing());
}

/* TODO: refactor and move this to application.js */
function clear_form() {
  $('#project_form').clearForm();
  $('#project_form input:text:first').focus();
}

/* TODO: refactor and move this to application.js */
function update_active_projects_container() {
  ProjectListPage.set_state_container_visibility('active', true);
  ProjectListPage.update_state_count('active', <%=@active_projects_count%>);
}

function html_for_project_listing() {
  return "<%= @saved ? js_render('project_listing', {}, @project) : "" %>";
}

<% end -%>

app/views/projects/destroy.js.erb
remove_deleted_project();
ProjectListPage.update_all_states_count(<%=@active_projects_count%>, <%=@hidden_projects_count%>, <%=@completed_projects_count%>)
TracksPages.page_inform("<%= t('projects.project_destroyed_status', name: @project.name) %>");
TracksPages.set_page_badge(<%=@down_count%>);

/* TODO: refactor and move function to application.js */
function remove_deleted_project() {
  TracksPages.slide_up_and_remove('div#<%=dom_id(@project, "container")%>');
}

app/views/projects/index.html.erb
<div id="display_box">
  <div id="projects-empty-nd" style="<%= @no_projects ? 'display:block' : 'display:none'%>">
    <div class="message"><p><%= t('projects.no_projects') %></p></div>
  </div>
  <%= render :partial => 'project_state_group', :object => @active_projects, :locals => { :state => 'active'} %>
  <%= render :partial => 'project_state_group', :object => @hidden_projects, :locals => { :state => 'hidden'} %>
  <%= render :partial => 'project_state_group', :object => @completed_projects, :locals => { :state => 'completed', :total_count => @completed_count} %>
</div>

<div id="input_box">
  <div id="project_new_project_filler">
    <%= render :partial => 'new_project_form' %>
  </div>
</div>

app/views/projects/index.m.erb
<h2><%= t('projects.active_projects') %></h2><%=
  render :partial => 'project_listing', :collection => @active_projects%>
<h2><%= t('projects.hidden_projects') %></h2><%=
  render :partial => 'project_listing', :collection => @hidden_projects %>
<h2><%= t('projects.completed_projects') %></h2><%=
  render :partial => 'project_listing', :collection => @completed_projects %>

app/views/projects/index.text.erb
<% @projects.each do |p| -%>

<%= p.name.upcase %>
<%= p.description + "\n" if p.description.present? -%>
<%= count_undone_todos_phrase_text(p)%>. Project is <%= p.state %>.
<% end -%>

app/views/projects/index_text_projects_and_actions.text.erb
<% @projects.each do |p| -%>
<%= p.name.upcase -%>
<% actions = p.todos.select { |t| t.active? } -%>
<%= render :partial => actions -%>
<% end -%>

app/views/projects/show.html.erb
<%
  deferred_pending_options = {:append_descriptor => nil, :parent_container_type => 'project'}
  done_todo_options = {
    :append_descriptor => t('projects.last_completed_in_project', :number=>prefs.show_number_completed),
    :suppress_project => true,
    :parent_container_type => 'project'
  }
  if @not_done_todos.count == 0
    # force project view so one empty container will be shown with an empty message
    @group_view_by = 'project'
  end
-%>
<div id="display_box">
  <%= project_next_prev %>

  <%= render :partial => "project_settings_container", :locals => {:project => @project} %>

  <%= empty_message_holder("not_done_context", @not_done_todos.empty?) %>

  <%= show_grouped_todos({:collapsible => false, :show_empty_containers => false, :parent_container_type => 'project' }) %>

  <%= show_deferred_pending_todos(@deferred_todos, @pending_todos, deferred_pending_options) %>

  <%= show_done_todos(@done, done_todo_options) unless @done.nil? %>

  <div class="container">
    <div id="notes">
      <div class="add_note_link link_in_container_header"><%= link_to t('projects.add_note'), '#' %> </div>
      <h2><%= t('projects.notes') %></h2>
      <div id="empty-n" style="display:<%= @project.notes.empty? ? 'block' : 'none'%>;">
        <div class="message"><p><%= t('projects.no_notes_attached') %></p></div>
      </div>
      <%= render :partial => "notes/notes_summary", :collection => @project.notes %>
    </div>
  </div>

  <div id="new-note" style="display:none;">
    <%= render :partial => "notes/note_edit_form", :object => @new_note, :locals => {:submit_text => t('projects.add_note_submit')} %>
  </div>

</div>

<div id="input_box">
  <%= render :partial => "shared/add_new_item_form" %>
  <%= render :file => "sidebar/sidebar" %>
</div>

app/views/projects/show.m.erb
<% project = @project %>
<%= project_next_prev_mobile %>
<h2><%=project.name%></h2>
<% if @project.description.present? -%>
<div class="project_description"><%= sanitize(@project.description) %></div>
<% end -%>
<ul class="c">
<%= render :partial => @not_done_todos, :locals => { :parent_container_type => "project" }%>
</ul>
<h2><%= t('projects.deferred_actions')%></h2>
<% if @deferred_todos.empty? -%>
<%= t('projects.deferred_actions_empty') %>
<% else -%>
<ul class="c">
<%= render :partial => @deferred_todos, :locals => { :parent_container_type => "project" }%>
</ul><% end
-%>
<h2><%= t('projects.completed_actions')%></h2>
<% if @done.empty? -%>
<%= t('projects.completed_actions_empty') %>
<% else -%>
<ul class="c">
<%= render :partial => @done, :locals => { :parent_container_type => "project" }%>
</ul><% end %>
<h2><%= t('projects.notes') %></h2>
<% if @project.notes.empty? -%>
<%= t('projects.notes_empty') %>
<% else -%><%= render :partial => "notes/notes_summary", :collection => @project.notes %>
<% end -%>
<h2><%= t('projects.settings') %></h2>
<%= t('projects.state', :state => project.aasm.current_state.to_s) %>. <%= @project_default_context %>